In [1]:
import pandas as pd

In [3]:
kaggle_metadata = pd.read_csv('./Resources/movies_metadata.csv', low_memory=False)
ratings = pd.read_csv('ratings.csv')

In [7]:
kaggle_metadata.sample(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
13928,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,20382,tt0833557,en,Visioneers,Visioneer George Washington Winsterhammerman l...,...,2008-06-12,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Visioneers,False,6.0,28.0
8292,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,210864,tt0424885,en,Celsius 41.11: The Temperature at Which the Br...,This film attempts to correct the record when ...,...,2004-10-22,0.0,72.0,[],Released,The truth behind the lies of Fahrenheit 9/11,Celsius 41.11: The Temperature at Which the Br...,False,9.0,1.0
22756,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,52147,tt0981352,tr,Ulak,NaN,...,2008-02-25,0.0,0.0,"[{'iso_639_1': 'tr', 'name': 'Türkçe'}]",Released,NaN,Ulak,False,5.7,9.0
44644,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,27221,tt0088412,de,Wo die grünen Ameisen träumen,Extraordinary images from Werner Herzog. Shot ...,...,1984-08-31,0.0,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Where the Green Ants Dream,False,7.1,10.0
27038,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",http://www.sonypictures.com/movies/squatters/,268321,tt2359307,en,Squatters,A wealthy couple from the Pacific Palisades di...,...,2014-05-14,0.0,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They want what they have.,Squatters,False,6.9,26.0